version: '3'
networks:
  java-docker-app-network:
    ipam: 
      driver: default
      config:
        - subnet: $ENV_SUBNET
services:
  java:
    image: $ENV_OPENJDK
    container_name: java-docker-app_$MODULE_NAME
    volumes:
      - ./bin/jar:/usr/src/app
      - ./app/resources/tomcat:/tmp
    working_dir: /usr/src/app
    command: java -jar $MODULE_NAME-$MODULE_VERSION.jar
    networks: 
      java-docker-app-network:
        ipv4_address: $MODULE_IP
    ports: 
      - $MODULE_PORT:8080