version: '3'
networks:
  java-app-network:
    ipam: 
      driver: default
      config:
        - subnet: $ENV_SUBNET
services:
  java:
    image: $ENV_OPENJDK
    container_name: java-app-$MODULE_NAME
    volumes:
      - ./../app/bin/jar:/usr/src/app/
    working_dir: /usr/src/app
    command: java -jar $MODULE_NAME-$MODULE_VERSION.jar
    networks: 
      java-app-network:
        ipv4_address: $MODULE_IP
    ports: 
      - $MODULE_PORT:8080